services:
  frontend:
    container_name: frontend
    build:
      context: ./src/frontend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - backend
    environment:
      - BACKEND_URL=http://backend:8081
      
  backend:
    container_name: backend
    build:
      context: ./src/backend
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - FRONTEND_URL=http://frontend:8080

