services:
  frontend:
    container_name: frontend
    build:
      context: ./src/frontend
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_BACKEND_URL: http://20.189.77.99:8081
    ports:
      - "8080:8080"
    depends_on:
      - backend
    environment:
      NEXT_PUBLIC_BACKEND_URL: http://20.189.77.99:8081  # Use dictionary style here

  backend:
    container_name: backend
    build:
      context: ./src/backend
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      NEXT_PUBLIC_FRONTEND_URL: http://20.189.77.99:8080  # Use dictionary style here
